apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pod
  labels:
    app: {{ .Release.Name }}

spec:
  containers:
    - name: {{ .Release.Name }}-container
      image: {{ .Values.container.image }}
      ports:
        - containerPort: {{ .Values.container.port }}